### ISSUE TITLE
Sharpen And Emboss

### ISSUE THREAD

**Issue by gargarchit** [mgautam98/Digital-Image-Processor#10]
I am Working on Sharpen and Emboss Filters

**Comment by mgautam98** [comment]
![image](https://user-images.githubusercontent.com/29784549/47239890-30e3e700-d404-11e8-9c05-da27ae1ee35c.png)


sharpen filter

**Comment by mgautam98** [comment]
Make the sharpen function flexible by passing 1 more argument %sharpness and change the kernel accordingly 100% means 5 in middle of kernel matrix

**Comment by gargarchit** [comment]
![download 1](https://user-images.githubusercontent.com/42545374/47254481-e2c0f900-d480-11e8-8d77-13f0d6133a7d.png)
