### ISSUE TITLE
Save functionality

### ISSUE THREAD

**Issue by mgautam98** [mgautam98/Digital-Image-Processor#9]
Any one want to work on save function. It will save the given image to output folder. Reply If you want to work else I will do it.

**Comment by gargarchit** [comment]
In this We have to save Output image in a folder in cloned repo folder?

**Comment by mgautam98** [comment]
We will have ./output outside src folder where outputs will be saved. save_img( ) function will be in utils.

**Comment by mgautam98** [comment]
imsave function is already present in matplotlib. Use it.

**Comment by mgautam98** [comment]
Just make a function in utils which saves in current working directory

**Comment by gargarchit** [comment]
Solved in Commit 71
